apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rsge-ingress
  namespace: rsge
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"  # nécessaire pour les signatures base64
spec:
  ingressClassName: nginx
  rules:
    - host: rsge.example.com   # remplacer par votre domaine
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rsge-frontend
                port:
                  number: 80
